### ISSUE TITLE
when run template got issue

### ISSUE THREAD

**Issue by bloomer99** [aws-quickstart/quickstart-poly-ccp#8]
then I run template I got errors : The following resource(s) failed to create: [CopyZips]. The following resource(s) failed to update: [S3BucketForWebsiteContent].

CopyZips: Received response status [FAILED] from custom resource. Message returned: See the details in CloudWatch Log Stream: 2023/05/25/[$LATEST]e6bb9e7b8c0b4881b40c8344e43511cc (RequestId: 9f74953d-ef7e-4a49-bb18-7344b08dc1ad)

BucketPolixy: Policy has invalid resource (Service: Amazon S3; Status Code: 400; Error Code: MalformedPolicy; Request ID: TK82V0DZM57QW7TT; S3 Extended Request ID: 4twPHP7xqVfEcGG075aAL41/KfaWVfM50SaoOLk+vknWeI1WASYUCqmiE4n5b+bR0QazkSbILUU=; Proxy: null)

**Comment by ledgerama** [comment]
Same problem here. I think the changes to default S3 bucket permissions has broken this. I got this working by changing the template, replacing the S3BucketForWebsiteContent section with the following

```
S3BucketForWebsiteContent:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
```
